name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - uses: "actions/checkout@v2"
      - uses: "home-assistant/actions/hassfest@master"
